// Guided project definitions.
//
// parts  — the reference layout. `at` is a grid cell (hole), wires give start
//          `at` and end `to`. Every non-wire part has a `ref` (V1, R1, D1…)
//          that the build steps and the Circuit Coach refer to.
// steps  — the build, in order. Each step is one of:
//            { place: 'R1' }                 put the part on the board
//            { connect: ['R1.1', 'LED1.A'] }   these two legs must be joined
//            { expect: { ref, pressed | on | lit | spinning | field } }  operate / observe it
// payoff — optional: 'radio' or 'walkie' opens a live panel once the build
//          is complete.
//          Leg names come from TERMINAL_NAMES in simulate.js:
//            PowerSupply + / -   LED & Diode A (anode) / K (cathode)
//            Resistor, Switch 1 / 2 (either way round)   Transistor C / B / E
// explore — things to try once it works.

export const PROJECTS = [
  {
    id: 'first-light',
    name: 'First Light',
    difficulty: 'Beginner',
    buildable: true,
    tagline: 'Light your first LED — the "hello world" of electronics.',
    learn: 'Every circuit needs a closed loop. The resistor limits current so the LED survives: I = (V − V_LED) / R ≈ (5 − 1.9) / 330 ≈ 9 mA.',
    parts: [
      { ref: 'V1', type: 'PowerSupply', at: [0, 0], value: 5 },
      { ref: 'R1', type: 'Resistor', at: [-5, 3], value: 330 },
      { ref: 'LED1', type: 'LED', at: [-7, 3], color: 'red' },
      { type: 'Wire', at: [-6, 3], to: [-6, 5] },
      { type: 'Wire', at: [-6, 5], to: [2, 5] },
      { type: 'Wire', at: [2, 5], to: [2, 3] },
    ],
    steps: [
      { place: 'V1', text: 'Place the DC power supply and leave it at 5 V. The red post is + and the black post is −.' },
      { place: 'R1', text: 'Place a resistor and set it to 330 Ω.' },
      { connect: ['V1.+', 'R1.2'], text: 'Slide R1 so one of its legs sits in the same hole as the red + post.' },
      { place: 'LED1', text: 'Place a red LED. Its + leg (anode) shows as a red dot when selected.' },
      { connect: ['R1.1', 'LED1.A'], text: 'Put the LED\'s + leg in the same hole as R1\'s free leg.' },
      { connect: ['LED1.K', 'V1.-'], text: 'Run jumper wire from the LED\'s − leg (cathode) back to the black − post. That closes the loop.' },
      { expect: { ref: 'LED1', lit: true }, text: 'The LED lights up. Click it: the meter reads about 9 mA.' },
    ],
    explore: [
      'Delete R1 and bridge the gap with a wire: the LED burns out. This is why LEDs need a resistor.',
      'Change R1 to 1 kΩ. The LED dims to about 3 mA.',
    ],
  },
  {
    id: 'push-button-light',
    name: 'Push-Button Light',
    difficulty: 'Beginner',
    buildable: true,
    tagline: 'A doorbell-style momentary switch controlling an LED.',
    learn: 'A switch simply opens or closes the loop. Open = infinite resistance, no current anywhere. Closed = a few milliohms, and the circuit springs to life.',
    parts: [
      { ref: 'V1', type: 'PowerSupply', at: [0, 0], value: 5 },
      { ref: 'R1', type: 'Resistor', at: [-5, 3], value: 330 },
      { ref: 'LED1', type: 'LED', at: [-7, 3], color: 'red' },
      { type: 'Wire', at: [-6, 3], to: [-6, 5] },
      { type: 'Wire', at: [-6, 5], to: [1, 5] },
      { ref: 'S1', type: 'Switch', at: [2, 5], pressed: false },
      { type: 'Wire', at: [3, 5], to: [2, 3] },
    ],
    steps: [
      { place: 'V1', text: 'Place the 5 V power supply.' },
      { place: 'R1', text: 'Place a 330 Ω resistor.' },
      { connect: ['V1.+', 'R1.2'], text: 'Put one of R1\'s legs in the red + post\'s hole.' },
      { place: 'LED1', text: 'Place a red LED.' },
      { connect: ['R1.1', 'LED1.A'], text: 'Put the LED\'s + leg (anode) in the same hole as R1\'s free leg.' },
      { place: 'S1', text: 'Place a push button below the supply.' },
      { connect: ['LED1.K', 'S1.1'], text: 'Run jumper wire from the LED\'s − leg to one leg of the button.' },
      { connect: ['S1.2', 'V1.-'], text: 'Run jumper wire from the button\'s other leg to the black − post.' },
      { expect: { ref: 'S1', pressed: true }, text: 'Click the button and press it. The loop closes.' },
      { expect: { ref: 'LED1', lit: true }, text: 'The LED lights while the button is held.' },
    ],
    explore: [
      'Release the button and click it. The meter shows the full 5 V sitting across the open gap.',
      'Press it again. The voltage across the button drops to almost 0 V.',
    ],
  },
  {
    id: 'parallel-leds',
    name: 'Parallel LEDs',
    difficulty: 'Beginner',
    buildable: true,
    tagline: 'Two LEDs, each on its own branch — like the lights in a house.',
    learn: 'In parallel, each branch gets the full supply voltage and works on its own. The supply provides the sum of the branch currents: about 9 mA + 9 mA = 18 mA. Unplug one branch and the other keeps shining.',
    parts: [
      { ref: 'V1', type: 'PowerSupply', at: [6, -2], value: 5 },
      { type: 'Wire', at: [4, 1], to: [-8, 3] },
      { ref: 'R1', type: 'Resistor', at: [-5, 3], value: 330 },
      { ref: 'LED1', type: 'LED', at: [-1, 3], color: 'red' },
      { type: 'Wire', at: [0, 3], to: [8, 1] },
      { type: 'Wire', at: [-8, 3], to: [-8, 5] },
      { ref: 'R2', type: 'Resistor', at: [-5, 5], value: 330 },
      { ref: 'LED2', type: 'LED', at: [-1, 5], color: 'green' },
      { type: 'Wire', at: [0, 5], to: [0, 3] },
    ],
    steps: [
      { place: 'V1', text: 'Place the 5 V power supply on the right side of the board.' },
      { place: 'R1', text: 'Place a 330 Ω resistor (R1) to the left, below the supply.' },
      { connect: ['V1.+', 'R1.1'], text: 'Run jumper wire from the red + post to R1\'s left leg.' },
      { place: 'LED1', text: 'Place a red LED (LED1) to the right of R1.' },
      { connect: ['R1.2', 'LED1.A'], text: 'Put LED1\'s + leg (anode) in the same hole as R1\'s right leg.' },
      { connect: ['LED1.K', 'V1.-'], text: 'Run jumper wire from LED1\'s − leg to the black − post. Branch 1 is complete.' },
      { expect: { ref: 'LED1', lit: true }, text: 'LED1 lights up.' },
      { place: 'R2', text: 'Branch 2: place another 330 Ω resistor (R2) two rows below R1.' },
      { connect: ['V1.+', 'R2.1'], text: 'Run jumper wire from R1\'s left leg (already on +) down to R2\'s left leg.' },
      { place: 'LED2', text: 'Place an LED (LED2) and make it green.' },
      { connect: ['R2.2', 'LED2.A'], text: 'Put LED2\'s + leg in the same hole as R2\'s right leg.' },
      { connect: ['LED2.K', 'V1.-'], text: 'Run jumper wire from LED2\'s − leg up to LED1\'s − leg. Both branches now share the return.' },
      { expect: { ref: 'LED2', lit: true }, text: 'Both LEDs are lit. Click the supply: it now delivers about 18 mA.' },
    ],
    explore: [
      'Delete R2. LED2 goes out, and LED1 keeps shining.',
      'Change R2 to 1 kΩ. Only the green LED dims.',
    ],
  },
  {
    id: 'voltage-divider',
    name: 'Voltage Divider',
    difficulty: 'Beginner+',
    buildable: true,
    tagline: 'Two resistors that split a voltage — the most used sub-circuit in electronics.',
    learn: 'Series resistors share the supply voltage in proportion to their resistance: V_out = V · R2/(R1+R2). Equal resistors split 9 V into 4.5 V + 4.5 V. Sensors, volume knobs, and reference voltages all start here.',
    parts: [
      { ref: 'V1', type: 'PowerSupply', at: [6, -2], value: 9 },
      { type: 'Wire', at: [4, 1], to: [-8, 3] },
      { ref: 'R1', type: 'Resistor', at: [-5, 3], value: 1000 },
      { ref: 'R2', type: 'Resistor', at: [1, 3], value: 1000 },
      { type: 'Wire', at: [4, 3], to: [8, 1] },
    ],
    steps: [
      { place: 'V1', text: 'Place the power supply on the right side of the board and set it to 9 V.' },
      { place: 'R1', text: 'Place a 1 kΩ resistor (R1) on the left.' },
      { connect: ['V1.+', 'R1.1'], text: 'Run jumper wire from the red + post to R1\'s left leg.' },
      { place: 'R2', text: 'Place a second 1 kΩ resistor (R2) to the right of R1.' },
      { connect: ['R1.2', 'R2.1'], text: 'Put R2\'s left leg in the same hole as R1\'s right leg. That shared hole is V_out.' },
      { connect: ['R2.2', 'V1.-'], text: 'Run jumper wire from R2\'s right leg to the black − post.' },
    ],
    explore: [
      'Click each resistor. Both read 4.5 V, with the same 4.5 mA through each.',
      'Change R1 to 2000 Ω. The split becomes 6 V across R1 and 3 V across R2.',
    ],
  },
  {
    id: 'polarity-protection',
    name: 'Reverse-Polarity Guard',
    difficulty: 'Beginner+',
    buildable: true,
    tagline: 'A diode that protects a circuit if the battery is put in backwards.',
    learn: 'A diode is a one-way valve for current. In series with the circuit it costs about 0.7 V, so the LED current falls to (5 − 0.7 − 1.9) / 330 ≈ 7 mA. In exchange, reversed power is blocked completely.',
    parts: [
      { ref: 'V1', type: 'PowerSupply', at: [6, -2], value: 5 },
      { type: 'Wire', at: [4, 1], to: [-8, 3] },
      { ref: 'D1', type: 'Diode', at: [-6, 3] },
      { ref: 'R1', type: 'Resistor', at: [-1, 3], value: 330 },
      { ref: 'LED1', type: 'LED', at: [3, 3], color: 'red' },
      { type: 'Wire', at: [4, 3], to: [8, 1] },
    ],
    steps: [
      { place: 'V1', text: 'Place the 5 V power supply on the right side of the board.' },
      { place: 'D1', text: 'Place a diode (D1) on the far left. The silver stripe marks the cathode (K).' },
      { connect: ['V1.+', 'D1.A'], text: 'Run jumper wire from the red + post to D1\'s anode (the end without the stripe).' },
      { place: 'R1', text: 'Place a 330 Ω resistor (R1) to the right of the diode.' },
      { connect: ['D1.K', 'R1.1'], text: 'Put one of R1\'s legs in the same hole as D1\'s striped end.' },
      { place: 'LED1', text: 'Place a red LED (LED1) to the right of R1.' },
      { connect: ['R1.2', 'LED1.A'], text: 'Put LED1\'s + leg in the same hole as R1\'s other leg.' },
      { connect: ['LED1.K', 'V1.-'], text: 'Run jumper wire from LED1\'s − leg to the black − post.' },
      { expect: { ref: 'LED1', lit: true }, text: 'The LED lights. Click D1: it drops about 0.7 V.' },
    ],
    explore: [
      'Click D1 and rotate it 180°. The LED goes out, because D1 now blocks the current. A backwards battery gets blocked the same way.',
      'Compare LED1\'s current with First Light (about 7 mA against 9 mA). The difference is the price of the diode\'s 0.7 V drop.',
    ],
  },
  {
    id: 'and-gate',
    name: 'AND Gate: Two-Hand Safety Switch',
    difficulty: 'Beginner+',
    buildable: true,
    tagline: 'The LED lights only when button 1 AND button 2 are held — like a machine that needs both hands on it.',
    learn: 'Switches in series make AND logic: current has one path, and each button is a gate on it. If either one is open, the loop is broken. This is the idea behind every digital logic gate.',
    parts: [
      { ref: 'V1', type: 'PowerSupply', at: [6, -2], value: 5 },
      { type: 'Wire', at: [4, 1], to: [-8, 3] },
      { ref: 'R1', type: 'Resistor', at: [-5, 3], value: 330 },
      { ref: 'LED1', type: 'LED', at: [-1, 3], color: 'red' },
      { ref: 'S1', type: 'Switch', at: [1, 3], pressed: false },
      { ref: 'S2', type: 'Switch', at: [3, 3], pressed: false },
      { type: 'Wire', at: [4, 3], to: [8, 1] },
    ],
    steps: [
      { place: 'V1', text: 'Place the 5 V power supply on the right side of the board.' },
      { place: 'R1', text: 'Place a 330 Ω resistor (R1) on the left.' },
      { connect: ['V1.+', 'R1.1'], text: 'Run jumper wire from the red + post to R1\'s left leg.' },
      { place: 'LED1', text: 'Place a red LED (LED1) to the right of R1.' },
      { connect: ['R1.2', 'LED1.A'], text: 'Put LED1\'s + leg in the same hole as R1\'s right leg.' },
      { place: 'S1', text: 'Place push button S1 to the right of the LED.' },
      { connect: ['LED1.K', 'S1.1'], text: 'Put one of S1\'s legs in the same hole as LED1\'s − leg.' },
      { place: 'S2', text: 'Place push button S2 right after S1.' },
      { connect: ['S1.2', 'S2.1'], text: 'Put one of S2\'s legs in the same hole as S1\'s other leg, so the buttons are in series.' },
      { connect: ['S2.2', 'V1.-'], text: 'Run jumper wire from S2\'s free leg to the black − post.' },
      { expect: { ref: 'S1', pressed: true }, text: 'Press S1. Nothing happens yet: S2 is still open.' },
      { expect: { ref: 'S2', pressed: true }, text: 'Now press S2 as well.' },
      { expect: { ref: 'LED1', lit: true }, text: 'Both buttons are pressed, so the LED lights.' },
    ],
    explore: [
      'Release either button and the LED goes out. Fill in the truth table: 00 → off, 01 → off, 10 → off, 11 → on.',
    ],
  },
  {
    id: 'or-gate',
    name: 'OR Gate: Two Doorbells',
    difficulty: 'Beginner+',
    buildable: true,
    tagline: 'Front door OR back door — either button lights the LED.',
    learn: 'Switches in parallel make OR logic: each button is its own path around the gap. Closing either one completes the loop.',
    parts: [
      { ref: 'V1', type: 'PowerSupply', at: [6, -2], value: 5 },
      { type: 'Wire', at: [4, 1], to: [-8, 3] },
      { ref: 'R1', type: 'Resistor', at: [-5, 3], value: 330 },
      { ref: 'LED1', type: 'LED', at: [-1, 3], color: 'yellow' },
      { ref: 'S1', type: 'Switch', at: [1, 3], pressed: false },
      { type: 'Wire', at: [2, 3], to: [8, 1] },
      { type: 'Wire', at: [0, 3], to: [0, 5] },
      { ref: 'S2', type: 'Switch', at: [1, 5], pressed: false },
      { type: 'Wire', at: [2, 5], to: [2, 3] },
    ],
    steps: [
      { place: 'V1', text: 'Place the 5 V power supply on the right side of the board.' },
      { place: 'R1', text: 'Place a 330 Ω resistor (R1) on the left.' },
      { connect: ['V1.+', 'R1.1'], text: 'Run jumper wire from the red + post to R1\'s left leg.' },
      { place: 'LED1', text: 'Place an LED (LED1) and make it yellow.' },
      { connect: ['R1.2', 'LED1.A'], text: 'Put LED1\'s + leg in the same hole as R1\'s right leg.' },
      { place: 'S1', text: 'Place push button S1 to the right of the LED.' },
      { connect: ['LED1.K', 'S1.1'], text: 'Put one of S1\'s legs in the same hole as LED1\'s − leg.' },
      { connect: ['S1.2', 'V1.-'], text: 'Run jumper wire from S1\'s other leg to the black − post.' },
      { place: 'S2', text: 'Place push button S2 two rows below S1.' },
      { connect: ['S1.1', 'S2.1'], text: 'Run a short jumper from S1\'s left leg down to S2\'s left leg.' },
      { connect: ['S1.2', 'S2.2'], text: 'Run a short jumper from S1\'s right leg down to S2\'s right leg. The buttons are now side by side, in parallel.' },
      { expect: { ref: 'S2', pressed: true }, text: 'Press S2 only. The LED lights, because either path is enough.' },
      { expect: { ref: 'LED1', lit: true }, text: 'The LED is lit through S2 alone.' },
    ],
    explore: [
      'Try S1 alone, then both at once. Truth table: 00 → off, 01 → on, 10 → on, 11 → on.',
      'With both pressed, click each button. They share the current between them.',
    ],
  },
  {
    id: 'transistor-switch',
    name: 'Transistor Switch',
    difficulty: 'Intermediate',
    buildable: true,
    tagline: 'A tiny base current switches a bigger collector current — the building block of amplifiers and computers.',
    learn: 'An NPN transistor conducts from collector to emitter when current flows into its base. About 4 mA into the base (through R2) can let up to β × 4 mA ≈ 400 mA through the collector. Here the LED only needs about 8 mA, so the transistor is fully on ("saturated") and acts like a closed switch.',
    parts: [
      { ref: 'V1', type: 'PowerSupply', at: [6, -2], value: 5 },
      { type: 'Wire', at: [4, 1], to: [-8, 3] },
      { ref: 'R1', type: 'Resistor', at: [-5, 3], value: 330 },
      { ref: 'LED1', type: 'LED', at: [-1, 3], color: 'green' },
      { ref: 'Q1', type: 'Transistor', at: [1, 3] },
      { type: 'Wire', at: [2, 3], to: [8, 1] },
      { type: 'Wire', at: [-8, 3], to: [-7, 5] },
      { ref: 'S1', type: 'Switch', at: [-6, 5], pressed: false },
      { ref: 'R2', type: 'Resistor', at: [-2, 5], value: 1000 },
      { type: 'Wire', at: [1, 5], to: [1, 3] },
    ],
    steps: [
      { place: 'V1', text: 'Place the 5 V power supply on the right side of the board.' },
      { place: 'R1', text: 'Load circuit: place a 330 Ω resistor (R1) on the left.' },
      { connect: ['V1.+', 'R1.1'], text: 'Run jumper wire from the red + post to R1\'s left leg.' },
      { place: 'LED1', text: 'Place a green LED (LED1) to the right of R1.' },
      { connect: ['R1.2', 'LED1.A'], text: 'Put LED1\'s + leg in the same hole as R1\'s right leg.' },
      { place: 'Q1', text: 'Place the NPN transistor (Q1). With no rotation its legs are C, B, E from left to right.' },
      { connect: ['LED1.K', 'Q1.C'], text: 'Put Q1\'s collector (C, left leg) in the same hole as LED1\'s − leg.' },
      { connect: ['Q1.E', 'V1.-'], text: 'Run jumper wire from Q1\'s emitter (E, right leg) to the black − post.' },
      { place: 'S1', text: 'Control circuit: place push button S1 on the bottom row.' },
      { connect: ['V1.+', 'S1.1'], text: 'Run jumper wire from R1\'s left leg (which is on +) to S1\'s left leg.' },
      { place: 'R2', text: 'Place a 1 kΩ base resistor (R2) to the right of S1.' },
      { connect: ['S1.2', 'R2.1'], text: 'Put one of R2\'s legs in the same hole as S1\'s right leg.' },
      { connect: ['R2.2', 'Q1.B'], text: 'Run jumper wire from R2\'s free leg up to Q1\'s base (B, middle leg).' },
      { expect: { ref: 'S1', pressed: true }, text: 'Press S1 to push a small current into the base.' },
      { expect: { ref: 'LED1', lit: true }, text: 'The transistor switches on and the LED lights. Click Q1 to compare base and collector current.' },
    ],
    explore: [
      'Change R2 to 100 kΩ. The base current drops to about 43 µA, so Q1 can only pass about 4 mA and the LED dims. The transistor is now amplifying, not just switching.',
      'Replace R2 with a plain wire (no base resistor). The base current shoots up and the Coach flags it.',
    ],
  },
  {
    id: "electromagnet",
    name: "Electromagnet",
    difficulty: "Beginner",
    buildable: true,
    tagline: "Turn a coil of wire into a magnet you can switch on and off.",
    learn: "Current flowing through a coil makes a magnetic field. Its strength is roughly turns × current (ampere-turns): 250 turns × 48 mA ≈ 12 ampere-turns. More turns or more current, stronger magnet. Cut the current and the field vanishes, which is how relays, speakers and electric motors work.",
    parts: [
      { ref: "V1", type: "PowerSupply", at: [0,0], value: 5 },
      { ref: "R1", type: "Resistor", at: [-5,3], value: 100 },
      { ref: "L1", type: "Coil", at: [-8,1], rotation: Math.PI / 2, value: 250 },
      { ref: "S1", type: "Switch", at: [-5,-4], pressed: false },
      { type: 'Wire', at: [-6,-4], to: [-8,-1] },
      { type: 'Wire', at: [2,3], to: [-4,-4] },
    ],
    steps: [
      {place: "V1",text: "Place the DC power supply and leave it at 5 V."},
      {place: "R1",text: "Place a resistor and set it to 100 Ω. It limits the current so the coil doesn't overheat."},
      {connect: ["V1.+","R1.2"],text: "Put one of R1's legs in the red + post's hole."},
      {place: "L1",text: "Place a wire coil and set it to 250 turns (Magnetism & Radio in Parts)."},
      {connect: ["R1.1","L1.1"],text: "Join R1's free leg to one end of the coil."},
      {place: "S1",text: "Place a push button: it will switch the magnet on and off."},
      {connect: ["L1.2","S1.1"],text: "Run a jumper from the coil's other end to one leg of the button."},
      {connect: ["S1.2","V1.-"],text: "Run a jumper from the button's other leg to the black − post."},
      {expect: {ref: "S1",pressed: true},text: "Press the button to close the loop."},
      {expect: {ref: "L1",field: true},text: "The coil glows blue: it's now a magnet. Click it to read the field in ampere-turns."},
    ],
    explore: [
      "Change the coil to 1000 turns: the field is four times stronger for the same current.",
      "Release the button. The field collapses instantly; that on/off control is what makes electromagnets so useful.",
      "Change R1 to 1 kΩ. Less current, weaker field.",
    ],
  },
  {
    id: "lemon-battery",
    name: "Lemon Battery",
    difficulty: "Beginner",
    buildable: true,
    tagline: "Make electricity from lemons, copper and zinc, and light an LED with it.",
    learn: "Two different metals in an acid make a cell: zinc gives up electrons more easily than copper, so electrons flow from the zinc to the copper through your circuit. One lemon cell makes about 0.95 V, not enough for a red LED (≈1.9 V), and the juice lets only a little current through (about 500 Ω inside each lemon). Stack cells in series and the voltages add up.",
    parts: [
      { ref: "B1", type: "Cell", at: [-6,0], metal: "zn-cu" },
      { ref: "B2", type: "Cell", at: [-2,0], metal: "zn-cu" },
      { ref: "B3", type: "Cell", at: [2,0], metal: "zn-cu" },
      { ref: "LED1", type: "LED", at: [5,0], rotation: Math.PI, color: "red" },
      { type: 'Wire', at: [-8,0], to: [6,0] },
    ],
    steps: [
      {place: "B1",text: "Place a battery cell (Power & Controls in Parts). It starts as a lemon with copper and zinc electrodes."},
      {place: "B2",text: "Place a second lemon cell next to it."},
      {connect: ["B1.-","B2.+"],text: "Join B1's zinc (−) electrode to B2's copper (+) electrode. That's a series connection: the voltages add."},
      {place: "B3",text: "Place a third lemon cell."},
      {connect: ["B2.-","B3.+"],text: "Join B2's zinc (−) to B3's copper (+)."},
      {place: "LED1",text: "Place a red LED."},
      {connect: ["B3.-","LED1.K"],text: "Join the last zinc (−) electrode to the LED's − leg (cathode)."},
      {connect: ["LED1.A","B1.+"],text: "Run a jumper from the LED's + leg (anode) back to the first copper (+) electrode."},
      {expect: {ref: "LED1",lit: true},text: "The LED glows faintly, powered by lemons. Click it: well under a milliamp, but enough to see."},
    ],
    explore: [
      "Delete B3. Two lemons make about 1.9 V minus what their juice wastes: not enough, and the LED goes dark.",
      "Add a fourth lemon in series: brighter.",
      "Switch the cells to zinc + carbon (dry cells). Two of those burn the LED out: dry cells have almost no internal resistance, so now the LED needs a resistor.",
    ],
  },
  {
    id: "generator",
    name: "Hand-Crank Generator",
    difficulty: "Beginner",
    buildable: true,
    tagline: "Spin a magnet next to a coil and light an LED with no battery at all.",
    learn: "Faraday's law: a changing magnetic field through a coil induces a voltage in it. Spin the magnet faster, or use more turns, and the voltage rises. This is exactly how power stations, bike dynamos and wind turbines make electricity. A spinning magnet makes alternating current (AC), so the LED lights on every other half-turn whichever way round it is.",
    parts: [
      { ref: "L1", type: "Coil", at: [0,0], value: 500 },
      { ref: "M1", type: "Magnet", at: [0,3], spinning: true, speed: 2 },
      { ref: "R1", type: "Resistor", at: [5,0], value: 220 },
      { ref: "LED1", type: "LED", at: [8,-1], rotation: Math.PI / 2, color: "red" },
      { type: 'Wire', at: [-2,0], to: [8,-2] },
    ],
    steps: [
      {place: "L1",text: "Place a wire coil and set it to 500 turns."},
      {place: "R1",text: "Place a 220 Ω resistor. On a fast spin the coil makes enough voltage to burn out a bare LED."},
      {connect: ["L1.2","R1.1"],text: "Join one end of the coil to one leg of R1."},
      {place: "LED1",text: "Place a red LED."},
      {connect: ["R1.2","LED1.A"],text: "Join R1's other leg to the LED's + leg (anode)."},
      {connect: ["LED1.K","L1.1"],text: "Run a jumper from the LED's − leg back to the coil's other end. The loop is closed, but nothing lights: there's no source yet."},
      {place: "M1",text: "Place a magnet within 5 holes of the coil."},
      {expect: {ref: "M1",spinning: true},text: "Click the magnet and tap Spin."},
      {expect: {ref: "LED1",lit: true},text: "The LED lights with no battery at all. Click the coil to read the voltage it's generating."},
    ],
    explore: [
      "Set the magnet to Slow: the voltage drops and the LED barely glows.",
      "Change the coil to 100 turns: only about 1 V even on Fast, too little for the LED. Generators need many turns.",
      "Move the magnet further than 5 holes away: the coil stops generating.",
    ],
  },
  {
    id: "fm-radio",
    name: "FM Radio Receiver",
    difficulty: "Advanced",
    buildable: true,
    payoff: "radio",
    tagline: "Build a one-transistor receiver, then tune in real stations.",
    learn: "The coil and capacitor form a tank circuit that resonates at f = 1 / (2π√(LC)). A 5-turn air coil (≈0.1 µH) with about 26 pF resonates near 99 MHz, right in the FM band. Tuning the capacitor moves that frequency across the band; the transistor amplifies what the antenna catches and drives the earphone. (Simplified: real FM receivers add a regenerative or discriminator stage to turn frequency changes into sound.)",
    parts: [
      { ref: "V1", type: "PowerSupply", at: [6,-2], value: 5 },
      { ref: "Q1", type: "Transistor", at: [0,1] },
      { ref: "SPK1", type: "Speaker", at: [-4,-1] },
      { ref: "R1", type: "Resistor", at: [-3,-4], value: 10000 },
      { ref: "L1", type: "Coil", at: [-7,2], rotation: Math.PI / 2, value: 5 },
      { ref: "C1", type: "Capacitor", at: [-4,3], rotation: Math.PI / 2 },
      { ref: "C2", type: "Capacitor", at: [-1,4], rotation: Math.PI },
      { ref: "ANT1", type: "Antenna", at: [-9,4] },
      { type: 'Wire', at: [-5,-1], to: [4,1] },
      { type: 'Wire', at: [-6,-4], to: [4,1] },
      { type: 'Wire', at: [-1,1], to: [-3,-1] },
      { type: 'Wire', at: [8,1], to: [1,1] },
      { type: 'Wire', at: [-4,2], to: [1,1] },
      { type: 'Wire', at: [-7,0], to: [1,1] },
      { type: 'Wire', at: [0,1], to: [0,-4] },
      { type: 'Wire', at: [0,4], to: [0,-4] },
      { type: 'Wire', at: [-4,4], to: [-7,4] },
      { type: 'Wire', at: [-2,4], to: [-7,4] },
      { type: 'Wire', at: [-9,4], to: [-7,4] },
    ],
    steps: [
      {place: "V1",text: "Place the power supply at 5 V."},
      {place: "Q1",text: "Place an NPN transistor. It amplifies the tiny signal the antenna catches."},
      {place: "SPK1",text: "Place an earphone (Magnetism & Radio in Parts)."},
      {connect: ["SPK1.1","V1.+"],text: "Join one leg of the earphone to the red + post."},
      {connect: ["SPK1.2","Q1.C"],text: "Join the earphone's other leg to the transistor's collector (C)."},
      {connect: ["Q1.E","V1.-"],text: "Join the emitter (E) to the black − post."},
      {place: "R1",text: "Place a 10 kΩ resistor to bias the transistor."},
      {connect: ["R1.1","V1.+"],text: "Join one leg of R1 to the red + post."},
      {connect: ["R1.2","Q1.B"],text: "Join R1's other leg to the base (B). The transistor is now switched partly on, ready to amplify."},
      {place: "L1",text: "Place a wire coil and set it to 5 turns: FM needs a small coil."},
      {place: "C1",text: "Place a capacitor next to the coil: together they form the tuning circuit."},
      {connect: ["L1.1","C1.+"],text: "Join the top of the coil to C1's + leg."},
      {connect: ["L1.2","C1.-"],text: "Join the bottom of the coil to C1's − leg. Coil and capacitor side by side make a tank circuit."},
      {connect: ["C1.-","Q1.E"],text: "Join the bottom of the tank to the emitter (the − side of the circuit)."},
      {place: "C2",text: "Place a second capacitor: it passes the radio signal to the base while blocking DC."},
      {connect: ["C2.-","C1.+"],text: "Join C2's − leg to the top of the tank."},
      {connect: ["C2.+","Q1.B"],text: "Join C2's + leg to the base (B)."},
      {place: "ANT1",text: "Place an antenna."},
      {connect: ["ANT1.1","L1.1"],text: "Join the antenna to the top of the tank. Done: open the radio and tune in."},
    ],
    explore: [
      "Open the radio panel and sweep the tuning: listen for the static between stations.",
      "Set the coil to 10 turns: the tank now resonates around 50 MHz, below the FM band, and the radio can't reach any station.",
    ],
  },
  {
    id: "walkie-talkie",
    name: "Walkie-Talkie Transmitter",
    difficulty: "Advanced",
    buildable: true,
    payoff: "walkie",
    tagline: "Build the talk side: a microphone driving a radio-frequency oscillator. The FM Radio build is the listen side.",
    learn: "The transistor and tank circuit oscillate at the tank's resonant frequency (the carrier). Your voice changes the microphone's voltage, which nudges that frequency up and down: frequency modulation. The antenna radiates it. The push button is the push-to-talk: the transmitter only has power while it's held. (Simplified: a working oscillator also needs a feedback capacitor from collector to emitter.)",
    parts: [
      { ref: "V1", type: "PowerSupply", at: [6,-2], value: 5 },
      { ref: "S1", type: "Switch", at: [1,-4], pressed: false },
      { ref: "Q1", type: "Transistor", at: [1,1] },
      { ref: "L1", type: "Coil", at: [-7,3], rotation: Math.PI / 2, value: 5 },
      { ref: "C1", type: "Capacitor", at: [-4,3], rotation: Math.PI / 2 },
      { ref: "R1", type: "Resistor", at: [-4,-2], value: 10000 },
      { ref: "MIC1", type: "Mic", at: [-9,-3], rotation: Math.PI / 2 },
      { ref: "R2", type: "Resistor", at: [-5,-4], value: 2200 },
      { ref: "C2", type: "Capacitor", at: [1,3] },
      { ref: "ANT1", type: "Antenna", at: [-1,5] },
      { type: 'Wire', at: [4,1], to: [0,-4] },
      { type: 'Wire', at: [-7,5], to: [2,-4] },
      { type: 'Wire', at: [-4,4], to: [2,-4] },
      { type: 'Wire', at: [-1,-2], to: [2,-4] },
      { type: 'Wire', at: [-2,-4], to: [2,-4] },
      { type: 'Wire', at: [-4,2], to: [-7,1] },
      { type: 'Wire', at: [0,1], to: [-7,1] },
      { type: 'Wire', at: [-1,5], to: [-7,1] },
      { type: 'Wire', at: [1,1], to: [-7,-2] },
      { type: 'Wire', at: [2,3], to: [-7,-2] },
      { type: 'Wire', at: [-9,-2], to: [-8,-4] },
      { type: 'Wire', at: [0,3], to: [-8,-4] },
      { type: 'Wire', at: [8,1], to: [2,1] },
      { type: 'Wire', at: [-9,-4], to: [2,1] },
    ],
    steps: [
      {place: "V1",text: "Place the power supply at 5 V."},
      {place: "S1",text: "Place a push button: it's your push-to-talk."},
      {connect: ["S1.1","V1.+"],text: "Join one leg of the button to the red + post."},
      {place: "Q1",text: "Place an NPN transistor: it will oscillate at radio frequency."},
      {connect: ["Q1.E","V1.-"],text: "Join the emitter (E) to the black − post."},
      {place: "L1",text: "Place a wire coil set to 5 turns."},
      {place: "C1",text: "Place a capacitor next to it for the tank circuit."},
      {connect: ["L1.1","S1.2"],text: "Join the top of the coil to the button's other leg: that's the switched power rail."},
      {connect: ["C1.+","L1.1"],text: "Join C1's + leg to the top of the coil."},
      {connect: ["C1.-","L1.2"],text: "Join C1's − leg to the bottom of the coil."},
      {connect: ["L1.2","Q1.C"],text: "Join the bottom of the tank to the collector (C)."},
      {place: "R1",text: "Place a 10 kΩ resistor to bias the base."},
      {connect: ["R1.2","S1.2"],text: "Join one leg of R1 to the switched power rail (the button's free leg)."},
      {connect: ["R1.1","Q1.B"],text: "Join R1's other leg to the base (B)."},
      {place: "MIC1",text: "Place a microphone."},
      {connect: ["MIC1.-","V1.-"],text: "Join the microphone's − leg to the black − post."},
      {place: "R2",text: "Place a 2.2 kΩ resistor: it powers the microphone."},
      {connect: ["R2.2","S1.2"],text: "Join one leg of R2 to the switched power rail."},
      {connect: ["R2.1","MIC1.+"],text: "Join R2's other leg to the microphone's + leg."},
      {place: "C2",text: "Place a capacitor to carry your voice to the transistor."},
      {connect: ["C2.+","MIC1.+"],text: "Join C2's + leg to the microphone's + leg."},
      {connect: ["C2.-","Q1.B"],text: "Join C2's − leg to the base (B)."},
      {place: "ANT1",text: "Place an antenna."},
      {connect: ["ANT1.1","Q1.C"],text: "Join the antenna to the collector: that's where the radio signal is strongest."},
      {expect: {ref: "S1",pressed: true},text: "Press and hold the button: the transmitter powers up. Open the walkie-talkie panel to talk."},
    ],
    explore: [
      "Release the button: the transmitter has no power, which is exactly how push-to-talk saves battery.",
      "Click the transistor while the button is held: it's in its active region, ready to amplify.",
    ],
  },
  {
    id: 'led-blinker',
    name: '555 LED Blinker (Clock)',
    difficulty: 'Intermediate',
    buildable: false,
    tagline: 'The classic first timer circuit — an LED that blinks on its own.',
    learn: 'A 555 timer charges and discharges a capacitor between two thresholds, producing a square wave. Needs transient (time-domain) simulation — coming soon.',
  },
];
