// Beginner project definitions. Positions are grid cells; wires give start
// and end cells. loadProject() in App converts cells to world coordinates.

export const PROJECTS = [
  {
    id: 'first-light',
    name: 'First Light',
    difficulty: 'Beginner',
    buildable: true,
    tagline: 'Light your first LED — the "hello world" of electronics.',
    learn: 'Every circuit needs a closed loop. The resistor limits current so the LED survives: I = (V − V_LED) / R ≈ (5 − 1.9) / 340 ≈ 9 mA.',
    steps: [
      'The 5 V supply pushes current out of its red + post.',
      'A 330 Ω resistor limits the current (without it the LED burns — try removing it!).',
      'Current enters the LED anode (red dot side) and lights it up.',
      'Jumper wires return the current to the black − post, closing the loop.',
    ],
    parts: [
      { type: 'PowerSupply', at: [0, 0], value: 5 },
      { type: 'Resistor', at: [-5, 3], value: 330 },
      { type: 'LED', at: [-7, 3] },
      { type: 'Wire', at: [-6, 3], to: [-6, 5] },
      { type: 'Wire', at: [-6, 5], to: [2, 5] },
      { type: 'Wire', at: [2, 5], to: [2, 3] },
    ],
  },
  {
    id: 'push-button-light',
    name: 'Push-Button Light',
    difficulty: 'Beginner',
    buildable: true,
    tagline: 'A doorbell-style momentary switch controlling an LED.',
    learn: 'A switch simply opens or closes the loop. Open = infinite resistance, no current anywhere. Closed = a few milliohms, and the circuit springs to life.',
    steps: [
      'Same LED loop as First Light, but with a push button in the return path.',
      'Select the button and tap Press — the loop closes and the LED lights.',
      'Release it and current stops instantly. Check the multimeter on the button: open, it drops all 5 V; closed, almost 0 V.',
    ],
    parts: [
      { type: 'PowerSupply', at: [0, 0], value: 5 },
      { type: 'Resistor', at: [-5, 3], value: 330 },
      { type: 'LED', at: [-7, 3] },
      { type: 'Wire', at: [-6, 3], to: [-6, 5] },
      { type: 'Wire', at: [-6, 5], to: [1, 5] },
      { type: 'Switch', at: [2, 5], pressed: false },
      { type: 'Wire', at: [3, 5], to: [2, 3] },
    ],
  },
  {
    id: 'voltage-divider',
    name: 'Voltage Divider',
    difficulty: 'Beginner+',
    buildable: true,
    tagline: 'Two resistors that split a voltage — the most used sub-circuit in electronics.',
    learn: 'Series resistors share the supply voltage in proportion to their resistance: V_out = V · R2/(R1+R2). Equal resistors split 9 V into 4.5 V + 4.5 V. Sensors, volume knobs, and reference voltages all start here.',
    steps: [
      'Current flows from + through R1, then R2, back to −.',
      'Select each resistor: the multimeter shows 4.5 V across each, same 4.5 mA through both.',
      'Change R1 to 2000 Ω in the inspector and watch the split become 6 V / 3 V.',
    ],
    parts: [
      { type: 'PowerSupply', at: [0, 0], value: 9 },
      { type: 'Resistor', at: [-5, 3], value: 1000 },
      { type: 'Wire', at: [-8, 3], to: [-8, -2] },
      { type: 'Resistor', at: [-5, -2], value: 1000 },
      { type: 'Wire', at: [-2, -2], to: [2, -2] },
      { type: 'Wire', at: [2, -2], to: [2, 3] },
    ],
  },
  {
    id: 'led-blinker',
    name: '555 LED Blinker (Clock)',
    difficulty: 'Intermediate',
    buildable: false,
    tagline: 'The classic first timer circuit — an LED that blinks on its own.',
    learn: 'A 555 timer charges and discharges a capacitor between two thresholds, producing a square wave. Needs transient (time-domain) simulation — coming soon.',
  },
  {
    id: 'fm-radio',
    name: 'FM Radio',
    difficulty: 'Advanced',
    buildable: false,
    tagline: 'Receive real broadcast radio with a coil, capacitor, and detector.',
    learn: 'An LC tank circuit resonates at f = 1/(2π√LC) to select a station. Needs AC analysis and inductors — coming soon.',
  },
  {
    id: 'walkie-talkie',
    name: 'Walkie-Talkie',
    difficulty: 'Advanced',
    buildable: false,
    tagline: 'A transmitter and receiver pair — two boards talking over the air.',
    learn: 'An oscillator generates a carrier, a microphone modulates it, and the antenna radiates it. Needs transistor amplification and AC simulation — coming soon.',
  },
];
